### ISSUE TITLE
[Bug]: InstalledVersions Exception - Remote Server

### ISSUE THREAD

**Issue by jpscharf** [beyondcode/tinkerwell-community#503]
### Operating system

macOS Catalina 10.15.7

### Laravel Version

v7.30.4

### PHP Version

Local: PHP 7.4.25 (cli) (built: Oct 23 2021 15:38:15) ( NTS ) / Remote:  PHP 7.4.6 (cli) (built: May 14 2020 10:02:44) ( NTS )

### Project Location

Remote (Server)

### Bug description

When attempting to run code in TinkerWell I get an exception related to `InstalledVersions.php`

### Steps to reproduce

1. Connect to Remote Server (SSH)
2. Run command in TinkerWell: `config('app')`
3. Get an Exception

### Relevant log output

```shell
ErrorException 

  include(phar:///tmp/tinker_compressed.phar/vendor/composer/../composer/InstalledVersions.php): failed to open stream: phar error: "vendor/composer/InstalledVersions.php" is not a file in phar "/tmp/tinker_compressed.phar"

  at phar:///tmp/tinker_compressed.phar/vendor/composer/ClassLoader.php:476
    472|  * Prevents access to $this/self from included files.
    473|  */
    474| function includeFile($file)
    475| {
  > 476|     include $file;
    477| }
    478|

      [2m+2 vendor frames [22m
  3   [internal]:0
      Composer\Autoload\ClassLoader::loadClass()

  4   [internal]:0
      spl_autoload_call()
```

**Comment by eronisko** [comment]
Same message for me on Windows 10 connecting remotely to Ubuntu 18.04.4.

After rolling back to v2.17.0 the issue goes away. v2.18.0 has this problem too.

**Comment by jpscharf** [comment]
Reviewed #502 manually ran `/tmp/tinker_compressed.phar` and received the following error:
```
PHP Notice:  Undefined offset: 1 in phar:///tmp/tinker_compressed.phar/index.php on line 5

Notice: Undefined offset: 1 in phar:///tmp/tinker_compressed.phar/index.php on line 5
PHP Fatal error:  Cannot declare interface _PhpScoperc223a629f245\Stringable, because the name is already in use in phar:///tmp/tinker_compressed.phar/vendor/symfony/polyfill-php80/Resources/stubs/Stringable.php on line 6

Fatal error: Cannot declare interface _PhpScoperc223a629f245\Stringable, because the name is already in use in phar:///tmp/tinker_compressed.phar/vendor/symfony/polyfill-php80/Resources/stubs/Stringable.php on line 6
```

**Comment by jpscharf** [comment]
Still an issue with 2.18.1

**Comment by mechelon** [comment]
Since you mentioned #502: Does this still happen with the latest version?

**Comment by mechelon** [comment]
I will close this issue due to inactivity.

If this issue still exists, feel free to reopen and, if applicable, provide more details.

**Comment by jpscharf** [comment]
This issue has started happening again:
- Laravel Framework 7.30.4
- PHP 7.4.28
- Composer version 2.2.7 2022-02-25 11:12:27 
- TinkerWell 2.23.0

I extracted `/tmp/forge_tinker.phar` and `vendor/composer/InstalledVersions.php` does not exist!

When I try to run `/tmp/forge_tinker.phar`
```
PHP Notice:  Undefined offset: 1 in phar:///tmp/forge_tinker.phar/index.php on line 5
PHP Fatal error:  Cannot declare interface _PhpScoperc223a629f245\Stringable, because the name is already in use in phar:///tmp/forge_tinker.phar/vendor/symfony/polyfill-php80/Resources/stubs/Stringable.php on line 6
```

Output in Tinkerwell
```
   ErrorException 

  include(phar:///tmp/forge_tinker.phar/vendor/composer/../composer/InstalledVersions.php): failed to open stream: phar error: "vendor/composer/InstalledVersions.php" is not a file in phar "/tmp/forge_tinker.phar"

  at phar:///tmp/forge_tinker.phar/vendor/composer/ClassLoader.php:571
    567|  * @private
    568|  */
    569| function includeFile($file)
    570| {
  > 571|     include $file;
    572| }
    573|

      [2m+2 vendor frames [22m
  3   [internal]:0
      Composer\Autoload\ClassLoader::loadClass()

  4   [internal]:0
      spl_autoload_call()
```
 
From Laravel log file:
```
[2022-03-07 17:58:15] production.ERROR: include(phar:///tmp/forge_tinker.phar/vendor/composer/../composer/InstalledVersions.php): failed to open stream: phar error: "vendor/composer/InstalledVersions.php" is not a file in phar "/tmp/forge_tinker.phar" {"exception":"[object] (ErrorException(code: 0): include(phar:///tmp/forge_tinker.phar/vendor/composer/../composer/InstalledVersions.php): failed to open stream: phar error: \"vendor/composer/InstalledVersions.php\" is not a file in phar \"/tmp/forge_tinker.phar\" at phar:///tmp/forge_tinker.phar/vendor/composer/ClassLoader.php:571)
[stacktrace]
#0 phar:///tmp/forge_tinker.phar/vendor/composer/ClassLoader.php(571): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 phar:///tmp/forge_tinker.phar/vendor/composer/ClassLoader.php(571): include()
#2 phar:///tmp/forge_tinker.phar/vendor/composer/ClassLoader.php(428): Composer\\Autoload\\includeFile()
#3 [internal function]: Composer\\Autoload\\ClassLoader->loadClass()
#4 [internal function]: spl_autoload_call()
#5 /home/forge/production.theperfumery.com/releases/20220209173110/vendor/spatie/laravel-ray/src/Ray.php(318): class_exists()
#6 /home/forge/production.theperfumery.com/releases/20220209173110/vendor/spatie/laravel-ray/src/Watchers/ApplicationLogWatcher.php(29): Spatie\\LaravelRay\\Ray->sendRequest()
#7 /home/forge/production.theperfumery.com/releases/20220209173110/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(381): Spatie\\LaravelRay\\Watchers\\ApplicationLogWatcher->Spatie\\LaravelRay\\Watchers\\{closure}()
#8 /home/forge/production.theperfumery.com/releases/20220209173110/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(226): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}()
#9 /home/forge/production.theperfumery.com/releases/20220209173110/vendor/laravel/framework/src/Illuminate/Log/Logger.php(210): Illuminate\\Events\\Dispatcher->dispatch()
#10 /home/forge/production.theperfumery.com/releases/20220209173110/vendor/laravel/framework/src/Illuminate/Log/Logger.php(176): Illuminate\\Log\\Logger->fireLogEvent()
#11 /home/forge/production.theperfumery.com/releases/20220209173110/vendor/laravel/framework/src/Illuminate/Log/Logger.php(123): Illuminate\\Log\\Logger->writeLog()
#12 /home/forge/production.theperfumery.com/releases/20220209173110/vendor/laravel/framework/src/Illuminate/Log/LogManager.php(591): Illuminate\\Log\\Logger->info()
#13 /home/forge/production.theperfumery.com/releases/20220209173110/resources/macros/Str/dash.php(17): Illuminate\\Log\\LogManager->info()
#14 /home/forge/production.theperfumery.com/releases/20220209173110/app/Providers/MacroServiceProvider.php(74): require_once('/home/forge/pro...')
#15 /home/forge/production.theperfumery.com/releases/20220209173110/app/Providers/MacroServiceProvider.php(48): App\\Providers\\MacroServiceProvider->registerMacros()
#16 /home/forge/production.theperfumery.com/releases/20220209173110/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\\Providers\\MacroServiceProvider->boot()
#17 /home/forge/production.theperfumery.com/releases/20220209173110/vendor/laravel/framework/src/Illuminate/Container/Util.php(37): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#18 /home/forge/production.theperfumery.com/releases/20220209173110/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#19 /home/forge/production.theperfumery.com/releases/20220209173110/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#20 /home/forge/production.theperfumery.com/releases/20220209173110/vendor/laravel/framework/src/Illuminate/Container/Container.php(596): Illuminate\\Container\\BoundMethod::call()
#21 /home/forge/production.theperfumery.com/releases/20220209173110/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(867): Illuminate\\Container\\Container->call()
#22 /home/forge/production.theperfumery.com/releases/20220209173110/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(850): Illuminate\\Foundation\\Application->bootProvider()
#23 [internal function]: Illuminate\\Foundation\\Application->Illuminate\\Foundation\\{closure}()
#24 /home/forge/production.theperfumery.com/releases/20220209173110/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(851): array_walk()
#25 /home/forge/production.theperfumery.com/releases/20220209173110/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\\Foundation\\Application->boot()
#26 /home/forge/production.theperfumery.com/releases/20220209173110/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(230): Illuminate\\Foundation\\Bootstrap\\BootProviders->bootstrap()
#27 /home/forge/production.theperfumery.com/releases/20220209173110/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(310): Illuminate\\Foundation\\Application->bootstrapWith()
#28 phar:///tmp/forge_tinker.phar/src/Drivers/LaravelTinkerwellDriver.php(24): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#29 phar:///tmp/forge_tinker.phar/index.php(41): LaravelTinkerwellDriver->bootstrap()
#30 /tmp/forge_tinker.phar(12): require('phar:///tmp/for...')
#31 {main}
"}
```
